campusthrift/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import  settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
import shop
import checkout
import views

urlpatterns = [



    url(r'^admin/', admin.site.urls),
    url(r'^logout$', views.logout_user, name='user_logout'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^shop/', include('shop.urls')),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.user_login, name='user_login'),
    url(r'^password_reset$', views.password_reset, name='password_reset'),
    url(r'^password_reset/(?P<uidb64>[\w|\W]+)$', views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^profile/edit$', views.profile_edit, name="profile_edit"),
    url(r'^profile/payment/edit$', views.payment_edit, name="payment_edit"),
    url(r'^profile/order/view/(?P<order_number>\w+)/$', views.order_view, name="order_view"),
    url(r'^profile/order/cancel/(?P<pk>\w+)/$', views.cancel_order, name="cancel_order"),
    url(r'^$', views.home, name='home'),
    url(r'^getdetails/', shop.views.getdetails),
    url(r'^activate/(?P<activation_key>\w+)$', views.activate, name="activate"),
    url(r'^user/(?P<user>\w+)$', views.user_store, name="user_store"),
    url(r'^about$', views.about, name='about'),
    url(r'^buyer_confirm/(?P<id>\w+)/$', views.buyer_confirm, name="buyer_confirm"),
    url(r'^seller_confirm/(?P<id>\w+)/$', views.seller_confirm, name="seller_confirm"),
    url(r'^5824710544$', views.github_push, name="github_push"),
    # url('^u/', include('upload.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'campusthrift.views.handler404'

shop/urls.py
from django.conf.urls import url
import views

urlpatterns = [

    url(r'^$', views.shop, name='shop'),
    url(r'^new$', views.new, name='new'),
    url(r'^view/(?P<pk>[0-9]+)/$', views.view_item, name="view_item"),
    url(r'^item/(?P<pk>[0-9]+)/delete$', views.delete_item, name="delete_item"),
    url(r'^cart/(?P<pk>[0-9]+)/delete$', views.cart_delete, name="delete_cart_item"),
    url(r'^category/(?P<category>\w+)/$', views.shop_category, name='shop_category'),
    url(r'category/(?P<category>.+?)/(?P<subcategory>.+?)/$', views.shop_subcategory, name='shop_subcategory'),
    url(r'^cart$', views.view_cart, name="view_cart"),

    # url(r'^')
]

shop/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.

ONCAMPUS = 1
OFFCAMPUS = 2
BOTH = 3

SHIPPING_CHOICES = (
    (ONCAMPUS, 'On Campus'),
    (OFFCAMPUS, 'Off Campus'),
    (BOTH, 'Both')
)

class Subcategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey("Category", related_name="subcategories")
    def __unicode__(self):
        return u'%s' % (self.name)

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __unicode__(self):
        return u'%s' % (self.name)

class ItemImage(models.Model):
    item = models.ForeignKey("Item", related_name='images')
    image = models.FileField(upload_to='uploads/')
    rotation = models.IntegerField(default=0)


class Item(models.Model):

    # This line is required. Links UserProfile to a User model instance.
    user = models.ForeignKey(User, related_name='seller')
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=5,decimal_places=2,validators=[
									MinValueValidator(0)])
    sold = models.BooleanField(default=False)
    shipping_price = models.DecimalField(max_digits=5,decimal_places=2,validators=[
									MinValueValidator(0)
    ])
    meeting_place = models.CharField(max_length=200, null=True, blank=True)
    category = models.CharField(max_length=200)
    sub_category = models.CharField(max_length=200)
    shipping = models.IntegerField(choices=SHIPPING_CHOICES)
    stripe_listing_fee_id = models.CharField(max_length=200)

shop/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.forms import modelformset_factory, BaseFormSet
from django import forms
import stripe
from campusthrift.settings import STRIPE_API_KEY
from users.models import UserProfile
from campusthrift.forms import ItemForm, ImageForm
from models import Category, Subcategory, Item, ItemImage
import simplejson
from PIL import Image
from decimal import *
from django.contrib.auth.decorators import login_required
stripe.api_key = STRIPE_API_KEY
from watson import search as watson
# Create your views here.
def shop(request):

    if 'q' in request.GET:

        items = watson.filter(Item, request.GET['q'])
        categories = Category.objects.all()

    else:
        items = Item.objects.all().filter(user__user__graduated=False, sold=False)
        categories = Category.objects.all()

    return render(request, 'shop/shop.html', {'items':items, 'categories':categories})

def shop_category(request, category):

    items = Item.objects.all().filter(sold=False,category=category, user__user__graduated=False)
    categories = Category.objects.all()
    return render(request, 'shop/shop.html', {'items':items, 'categories':categories})

def shop_subcategory(request, category, subcategory):

    category = category.replace("%20", ' ')
    subcategory = subcategory.replace("%20", ' ')

    items = Item.objects.all().filter(category=category,sold=False, sub_category=subcategory, user__user__graduated=False)
    categories = Category.objects.all()

    return render(request, 'shop/shop.html', {'items': items, 'categories': categories})


def cart_delete(request, pk):

    cart = request.session.get('cart', {})
    try:
        del cart[pk]
        request.session['cart'] = cart
        return redirect('view_cart')
    except:
        return redirect('view_cart')


def delete_item(request, pk):

    errors = []



    if Item.objects.filter(pk=pk).exists():
        if Item.objects.get(pk=pk).user == request.user:
            Item.objects.filter(pk=pk).delete()

    return redirect('profile')





@login_required(login_url='/login')
def new(request):

    errors = []

    if request.method == "POST":


        form = ItemForm(request.POST)

        saved_item = None

        if form.is_valid():
            item = form.save(commit=False)
            item.user = request.user
            ##Adding stripe fee to item total.
            item.price = Decimal(item.price) + Decimal(.30)
            item.save()
            item.category = request.POST['selectcategories']
            item.sub_category = request.POST['selectsubcategories']
            saved_item = item


        imageForm = ImageForm(request.POST, request.FILES)
        print imageForm
        if len(request.FILES) != 0 and saved_item:

            # raise forms.ValidationError(("At least one image is required for new listings."))

            for image in request.FILES:

                new_image = ItemImage()
                new_image.image = request.FILES[image]
                new_image.rotation = request.POST[str(image).replace("picture", "rotation")]
                new_image.item = saved_item
                new_image.save()

                im = Image.open(new_image.image)
                rotated_image = im.rotate(-1 * float(new_image.rotation))
                rotated_image.save(new_image.image.file.name, overwrite=True)


            if request.user.user.listed_first_item:

                #No longer charging listing fee.
                saved_item.stripe_listing_fee_id = "NOFEE"
                saved_item.save()

                # result = stripe.Charge.create(
                #        amount = int(50),
                #        currency = "usd",
                #        customer = request.user.user.stripe_customer_id,
                #        description = "Listing fee for " + saved_item.title
                # )
                # saved_item.stripe_listing_fee_id = result.id
                # saved_item.save()
            else:
                request.user.user.listed_first_item = True
                request.user.user.save()
                saved_item.stripe_listing_fee_id = "FIRSTTIME"
                saved_item.save()

            return redirect('shop')
            # print request.FILES[image]
        else:
            errors.append("You must upload at least one image!")

        if not saved_item:
            errors.append("Looks like your submission was incomplete!")
    else:
        form =ItemForm()
        imageForm = ImageForm()
    items = Category.objects.all()

    ImageFormSet = modelformset_factory(ItemImage, form=ImageForm, max_num=10, min_num=1, validate_min=True)

    formset = ImageFormSet(queryset=ItemImage.objects.none())

    return render(request, 'shop/new.html', {'form':form, 'categories': items, 'imageForm': imageForm, 'formset': formset, 'error':errors})


@login_required(login_url='/login')

def view_cart(request):

    cart = request.session.get('cart', {})
    item_list = []
    for id in cart:
        try:
            item = Item.objects.get(pk=id)
            item_list.append(item)
        except:
            pass


    return render(request, 'shop/cart.html', {'cart': item_list})
    # rest of the view



def view_item(request, pk):

    if request.method == "POST":

        item = request.POST['item']

        #Add one item to cart.
        cart = request.session.get('cart', {})
        cart[item] = 1
        request.session['cart'] = cart

        return redirect('view_item', pk)

    else:

        item = None


        try:
            item = Item.objects.get(pk=pk)

        except:
            pass

        if item:
            pictures = item.images.all()

            return render(request, 'shop/view.html', {'item':item, 'seller':item.user.user, 'pictures':pictures})



def getdetails(request):
    #country_name = request.POST['country_name']
    print(request.body)
    category_name = request.GET['cnt']
    print category_name

    # print(request.data)

    result_set = []
    all_subcategories = []
    answer = str(category_name[1:-1])
    selected_category = Category.objects.get(name=answer)

    all_subcategories = selected_category.subcategories.all()
    for subcategory in all_subcategories:

        result_set.append({'name': subcategory.name})

    return HttpResponse(simplejson.dumps(result_set), content_type='application/json')

shop/templates/shop/cart.html
{% extends "campusthrift/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block content %}
    <style>

        .error {
            margin: 40px;
            text-align: center;
        }

        .error-code {
            bottom: 60%;
            color: #2d353c;
            font-size: 96px;
            line-height: 100px;
        }

        .error-desc {
            font-size: 12px;
            color: #647788;
        }

        .m-b-10 {
            margin-bottom: 10px !important;
        }

        .m-b-20 {
            margin-bottom: 20px !important;
        }

        .m-t-20 {
            margin-top: 20px !important;
        }

    </style>

    <div class="content11">
<div class="cart-items">
	<div class="container11">
			 <h2>My Shopping Backpack</h2>

            {% if cart %}

             {% for item in cart %}

                 <div class="cart-header">
				 <div class="close1"> </div>
				 <div class="cart-sec simpleCart_shelfItem">
						<div class="cart-item cyc">
							 <img src="{{ item.images.all.0.image.url }}" class="img-responsive" style="max-height: 175px;" alt="">
						</div>
					   <div class="cart-item-info">
						<h3><a href="/shop/view/{{ item.pk }}"> {{ item.title }} </a></h3>
                       <a href="/shop/cart/{{ item.pk }}/delete" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash

"></span></a>
                       <div class="clearfix"></div>
						<ul class="qty">
							<li><p>Campus Information:</p></li>

                                {% if item.shipping == 1 or item.shipping == 3 %}
                                    <li><p>
                                    Campus: {{ item.user.user.school }}, Meeting Place: {{ item.meeting_place }}
                                    </p></li>
                                {% endif %}

						</ul>
                        <ul class="qty">
							<li><p>Deliver Options:</p></li>
							<li><p>
                                    {% if item.shipping == 1 %}
                                        On Campus Pickup Only
                                    {% elif item.shipping == 2 %}
                                        Off Campus Shipping Only
                                    {% else %}
                                        Off Campus Shipping or On Campus Pickup
                                    {% endif %}
                            </p></li>
						</ul>
							 <div class="delivery">

							 <span>${{ item.price }}</span>
							 <div class="clearfix"></div>
				        </div>
					   </div>
					   <div class="clearfix"></div>

				  </div>
			 </div>

             {% endfor %}

                                 <a href="/checkout" class="btn btn-primary pull-right">Checkout <i class="fa fa-angle-right"></i></a>
            {% else %}
                <div class="error">
                                        <div class="error-code m-b-10 m-t-20"><img src="{% static "images/cactuslooking.png" %}"></div>
                                        <h3 class="font-bold">We couldn't find any items in your cart..</h3>

                                        <div class="error-desc">
                                            Sorry, but it looks like your cart is empty. Try adding some from the shop page. <br>
                                            Happy Thrifting!
                                            <div>
                                                <a class=" login-detail-panel-button btn" href="/shop">
                                                    <i class="fa fa-arrow-left"></i>
                                                    Go back to Shop
                                                </a>
                                            </div>
                                        </div>
                                    </div>
            {% endif %}

    </div>
</div>

{#    <div id="login-overlay" class="modal-dialog modal-lg" style="width: 80%">#}
{#        <div class="modal-content">#}
{#            <div class="modal-header">#}
{#                <h4 class="modal-title" id="myModalLabel">Cart</h4>#}
{#            </div>#}
{#            <div class="modal-body">#}
{##}
{#            {% if cart %}#}
{##}
{#                <table id="cart" class="table table-hover">#}
{#                    <thead>#}
{#                    <tr>#}
{#                        <th>Product</th>#}
{#                        <th>Price</th>#}
{#                        <th>Actions</th>#}
{#                    </tr>#}
{#                    </thead>#}
{#                    <tbody>#}
{#                    {% for item in cart %}#}
{#                        <tr>#}
{#                            <td data-th="Product">#}
{#                                <div class="row">#}
{#                                    <div class="col-sm-2 hidden-xs"><img src="{{ item.images.all.0.image.url }}"#}
{#                                                                         alt="..." class="img-responsive"/></div>#}
{#                                    <div class="col-sm-10">#}
{#                                        <h4 class="nomargin">{{ item.title }}</h4>#}
{#                                        <p>{{ item.description|truncatechars:100 }}</p>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </td>#}
{#                            <td data-th="Price">${{ item.price }}</td>#}
{#                            <td class="actions" data-th="">#}
{#                                <a href="/shop/cart/{{ item.pk }}/delete" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>#}
{#                            </td>#}
{#                        </tr>#}
{#                    {% endfor %}#}
{#                    </tbody>#}
{##}
{##}
{#                </table>#}
{#            {% else %}#}
{#                <h4 class="text-center">It looks like your cart is empty. Visit the store and add some items! Happy thrifting!</h4>#}
{#                <br>#}
{#            {% endif %}#}
{#                <a href="/shop" class="btn btn-warning pull-left"><i class="fa fa-angle-left"></i> Continue Shopping</a>#}
{#                {% if cart %}#}
{#                     <a href="/checkout" class="btn btn-success pull-right">Checkout <i class="fa fa-angle-right"></i></a>#}
{#                {% else %}#}
{#                     <a href="/checkout" class="btn btn-success pull-right disabled">Checkout <i class="fa fa-angle-right"></i></a>#}
{#                {% endif %}#}
{##}
{##}
{##}
                {#                        {% for item in cart %}#}
                {#                            <div class="row">#}
                {#                                <div class="col-md-6">#}
                {#                                    <div class="cart-item-detail">#}
                {#                                        <h4>{{ item.title }}</h4>#}
                {#                                        <img src="{{ item.images.all.0.image.url }}" height="100px" width="100px">#}
                {#                                    </div>#}
                {#                                    <div class="cart-seller-detail">#}
                {#                                        <h4>Sold by:</h4>#}
                {#                                        <p>{{ item.user.first_name }}</p>#}
                {#                                        <p>{{ item.user.username }}</p>#}
                {#                                    </div>#}
                {#                                    <div class="cart-remove">#}
                {#                                        Delete#}
                {#                                    </div>#}
                {##}
                {##}
                {#                                </div>#}
                {#                                <div class="col-md-6">#}
                {##}
                {#                                    <i class="fa fa-times-circle-o pull-right" aria-hidden="true"></i>#}
                {#                                    <div class="pull-right">#}
                {#                                        <h4>Price:</h4>#}
                {#                                        <p>{{ item.price }}</p>#}
                {#                                        <h4>Shipping Price:</h4>#}
                {#                                        <p>{{ item.shipping_price }}</p>#}
                {#                                    </div>#}
                {##}
                {#                                </div>#}
                {#                            </div>#}
                {#                            <hr>#}
                {#                        {% endfor %}#}
{##}
{##}
                {#                    {{ request.session.cart|length }}#}
{##}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}





{% endblock content %}

shop/templates/shop/new.html
{% extends "campusthrift/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block content %}

    <div class="content11">
        <div class="main-1">
            <div class="container11">
                <div class="login-page">
                    <div class="account_grid">
                        {% if error %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                {{ error }}
                            </div>

                        {% endif %}
                        <div class="col-xs-12">
                            <div class="well">
                                <form id="loginForm" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form | crispy }}

                                    <div class="form-group">
                                        <label for="selectcategories">Category:</label>

                                        <select class="form-control" name="selectcategories" id="selectcategories">
                                            {% for item in categories %}
                                                <option val="{{ item.name }}"> {{ item.name }} </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="selectsubcategories">Subcategory:</label>
                                        <select class="form-control" name="selectsubcategories"
                                                id="selectsubcategories">


                                        </select>
                                        {% csrf_token %}
                                        {% for hidden in postForm.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}

                                        {% for field in postForm %}
                                            {{ field }} <br/>
                                        {% endfor %}

                                        <br>
                                        <label for="picture-0">Images:</label>
                                        <input id="picture-0" type="file" name="picture-0" accept="image/*"
                                               onchange="displayImage(this); readURL(this)">
                                        <input id="rotation-0" type="hidden" name="rotation-0" value="0">
                                        <br>
                                        <a class="add">Add additional images</a>

                                    </div>
                                    <p class="small"> Note, we will tack on $.30 to your item price
                                        when you list it which will cover your processing fees. Once your item sells, we will take 15% of the sale
                                    plus the $0.30 added to your item and you keep the rest! Sales will be credited to the debit card you have on file.</p>
                                    <button type="submit" style="border: 0; background: transparent">
                                        <img src="../../../static/images/submit.png" alt="submit"/>
                                    </button>
                                </form>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>



    <script>

        $(document).ready(function () {
            $('#id_meeting_place').hide();
            $('label[for="id_meeting_place"]').hide();

            $('#id_shipping').change(function () {

                if ($(this).val() != 2) {
                    $('#id_meeting_place').show();
                    $('label[for="id_meeting_place"]').show();
                } else {
                    $('#id_meeting_place').hide();
                    $('label[for="id_meeting_place"]').hide();
                }
            });
        });


        $(".add").click(function () {

            var divs = $('[id ^=rotation-]');

            var last = divs.length - 1;

            var last_id = divs[last].id;

            var next = last + 1;
            if (last < 4) {
                $('#' + last_id).after('<input onchange="displayImage(this); readURL(this)" id="picture-' + next + '" type="file" name="picture-' + next + '" accept="image/*"> ' +
                        '<input id="rotation-' + next + '" type="hidden" name="rotation-' + next + '" value="0"><br>')
            }
            else {
                alert("You may only upload a maximum of 5 images.")
            }


        });

        var rotateLeft = function (e) {
            var classList = e.className.split(/\s+/);
            console.log(classList);
            for (var i = 0; i < classList.length; i++) {

                if (classList[i] !== 'btn') {

                    rotation_string = classList[i].replace("img", "rotation");
                    original_image_string = classList[i];


                    $(document).ready(function () {
                        $("#rotation-0").val(parseInt($("#rotation-0").val()) - 90);
                        console.log($("#rotation-0").val());
                        console.log("." + original_image_string);

                        $("." + original_image_string).filter("img").css("transform", "rotate(" + $("#rotation-0").val() + "deg)");
                    });
                }
            }
        };
        var rotateRight = function (e) {
            var classList = e.className.split(/\s+/);
            console.log(classList);
            for (var i = 0; i < classList.length; i++) {

                if (classList[i] !== 'btn') {

                    rotation_string = classList[i].replace("img", "rotation");
                    original_image_string = classList[i];

                    $(document).ready(function () {
                        $("#rotation-0").val(parseInt($("#rotation-0").val()) + 90);
                        console.log($("#rotation-0").val());
                        console.log("." + original_image_string);

                        $("." + original_image_string).filter("img").css("transform", "rotate(" + $("#rotation-0").val() + "deg)");
                    });
                }
            }
        };
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();


                reader.onload = function (e) {

                    var class_string = ".img_prev" + input.getAttribute('id')

                    var preview_image = $(class_string);

                    $(class_string).attr('src', e.target.result);

                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        ;

        var displayImage = function (element) {


            var groupNumber = element.getAttribute('id').split('-')[1];
            var id = element.getAttribute('id');

            $('.img_prev' + id).remove();

            class_string = "img_prev" + id;

            $("#" + id).after('<img class=img_prev' + id + ' height=\'100px\' width=\'100px\' src=\'\'>');


            $(".img_prev" + id).after('<br><button type="button" onclick="rotateLeft(this); return false;"" class="btn img_prev' + id + '" style="margin-right: 5px""><i class="fa fa-rotate-left" aria-hidden="true"></i></button><button type="button" class="btn img_prev' + id + '" onclick="rotateRight(this); return false;"" style="margin-left: 5px"><i class="fa fa-rotate-right" aria-hidden="true"></i></button><br>');

            readURL(this);


        };

    </script>
    <script>
        $(document).ready(function () {
            $("#selectcategories").prop("selectedIndex", -1);
            $('select#selectcategories').change(function () {
                var optionSelected = $(this).find("option:selected");
                var valueSelected = optionSelected.val();
                var category_name = optionSelected.text();

                $.ajax({
                    url: '/getdetails', data: {'cnt': category_name}, success: function (result) {
                        $("#selectsubcategories option").remove();
                        for (var i = result.length - 1; i >= 0; i--) {
                            $("#selectsubcategories").append('<option>' + result[i].name + '</option>');
                        }
                    }
                });


            });
        });
    </script>



{% endblock content %}